module.exports = {
    "awkwardness": "Awkwardness X: Reduce the energy defense of the target by X points until the end of the round.",
    "dazzle": "Dazzle X: Reduce the mental defense of the target by X points until the end of the round or the target's next activation, whichever comes first.",
    "distract": "Distract X: Reduce the physical defense of the target by X points until the end of the round or the target's next activation, whichever comes first.",
    "ensnare": "Ensnare X: Reduce the speed of the target by X points until the end of the round. If the speed value is reduced to 0, the target character cannot move.",
    "explosive": "Explosive X: When this attack successfully hits, the attack affects an area with a radius of X centered on the target. Roll to hit for each model affected, friend or foe, within that radius in all directions. Models within the explosive area (but not the original target) may make an Agility roll. If this roll is passed, they receive only half damage from the attack, rounding fractions down (to a minimum of 1 point of damage).",
    "homing": "Homing: Attacks with this special rule do not require line of sight. Measure a clear trajectory around any intervening scenery or models.",
    "irresistible": "Irresistible: Ignore any resistance the target may have to the damage type of this attack.",
    "penetrative" : "Penetrative: Attacks with this rule ignore scenery and cover bonuses (line of sight may be required as usual depending upon the type of the attack). If the trajectory passes through a scenery piece, that object will take damage, but will not block the attack. (Remember that scenery can´t suffer Mental Nature damage).",
    "pierce": "Pierce X: When using this attack, continue measuring the line of the shot X inches beyond the target. This attack damages the target and other models or scenery in a dead straight line behind it, up to X. You still roll to hit additional targets",
    "push": "Push X: Displace the target miniature directly away from the attacker along the trajectory of the attack X inches, stopping if it comes into contact with something of a larger size. The target miniature is considered thrown and causes damage equal to size but doesn't receive overwhelm damage or become KD unless otherwise stated.",
    "stun": "Remove X power counters from the target, to a minimum of 0.",
    "acrobat": "Acrobat: Model may reroll failed agility rolls.",
    "agile": "Agile: This model can make one extra movement action per round.",
    "assassin": "Assassin: If this character scores a double 8 on a to hit roll doing a melee or ranged attack, the base damage of that attack is doubled.",
    "brutal": "Brutal: If this character scores a critical hit for a melee attack, the attacker may choose to apply the Push 4 effect to the target in addition to the usual plus one to damage.",
    "cruel": "Cruel: If the target character’s Endurance is in the red zone after this attack is resolved, add 1 to the damage caused.",
    "fly": "Fly: This character may move in any direction, even vertically, to land on a higher or lower level of the tabletop. The character never takes damage from falling but may still become knocked down. In addition, the character gains a plus one bonus to Defense against melee attacks from models without the Fly Skill (if a model loses the Fly skill for any reason, it also loses it’s third Speed value).",
    "great strategist" : "Great Strategist: At the start of the game, add an extra counter for your side to the initiative bag.",
    "immunity": "Immunity X: This character can’t be damaged or affected by attacks/powers with the X nature or damage type.",
    "infiltrator": "Infiltrator: During deployment, this model may be placed anywhere on the game board where its base will fit but not in contact with an enemy model’s volume.",
    "invisible": "Invisible: This model cannot be seen by models more than 1 inch away.",
    "leadership": "Leadership X: Friendly models within X with a base Power value lower than this character’s will gain one bonus Power counter when they are activated. A character that has this ability cannot benefit from this rule.",
    "luck": "Luck: Once per Round, this character may reroll any one die.",
    "marksmanship": "Marksmanship: This character gains plus one to their hit rolls on all ranged attacks.",
    "master fighter": "Master Fighter: This character may reroll one of the hit dice each time they make a hit roll.",
    "master tactician": "Master Tactician: At the end of this model’s activation, make a Willpower roll. If successful, you can activate another model immediately. This allows you to activate two characters consecutively, ignoring the usual sequence of play.",
    "mastermind": "Mastermind: At the start of the game, add an extra counter for your side to the initiative bag and remove one of your opponent’s counters.",
    "metallic": "Metallic: When this model receives the Stun effect, it reduces the effect applied by 1.",
    "order": "At the end of this character’s activation, you may choose a friendly model within 5 inches, in line of sight, that has not yet been activated. That model may immediately take its activation. This allows you to activate two characters consecutively, ignoring the usual sequence of play.",
    "perfect plan": "Perfect Plan: Once per game, at the start of the Initiative phase, look into the Initiative bag and draw a counter of your choice. Alternatively, you may use this ability to counter the Perfect Plan ability from an enemy character.",
    "phase shift": "Phase Shift: This character can pass through solid scenery elements or miniatures when he moves as if they weren’t there, but can’t end his movement in a place where his base can’t fit (for example inside a wall), or overlapping another miniature’s position.",
    "rage": "Rage X: When this character recovers from knock out, it immediately gains an additional X Power counters.",
    "regeneration": "Regeneration X: This character recovers X Endurance points at the start of the Power phase. Endurance points cannot exceed their starting value in this way.",
    "resistance": "Resistance X vs Y: When this character suffers any kind of damage of the Y nature or damage type, it is reduced by X points.",
    "scientific": "Scientific: This model may reroll failed Willpower rolls.",
    "soldier": "Soldier: This model may reroll failed Stamina rolls.",
    "stealth": "Stealth: This model cannot be seen by models more than 8 inches away.",
    "strategist": "Strategist: This character may pass on activating once per round, even if the controlling player has no passes remaining.",
    "thermal vision": "Thermal Vision: This character ignores the Invisible and Stealth abilities.",
    "toughness": "Toughness X: The character with this ability has the following special features: His size is increased (or reduced if the number is negative) by X. In addition, the distance this character can be pushed or thrown is also reduced by X inches.",
    "total vision": "Total Vision: This character can draw line of sight to any point on the gaming area ignoring effects, scenery, Invisible, and Stealth rules.",
    "wall crawler": "Wall-Crawler: A character with this ability suffers no penalty to their movement while climbing, and can end their movement in any part of the gaming area, even if their base does not fit. The character may not end their movement in a space occupied by other character. Mark the exact position of the miniature with a counter.",
    "weakness": "Weakness X: If this character suffers any kind of damage of X nature or damage type, the damage received is doubled. This rule cancels any resistance or immunity abilities the character may have.",
    "close combat master" : "Close combat master: This character may reroll one of the dice To Hit each time they make a Melee To Hit roll.",
    "comrade" : "Comrade X: Unactivated Character X can be activated immediately after the character with the Comrade ability. This allows you to activate two characters consecutively, bypassing the usual sequence of play.",
    "defensive teamwork" : "Defensive Teamwork: When this character is in contact with one or more friendly characters, those friendly characters gain plus one to Physical and Energy defenses. This bonus doesn't Stack.",
    "elite fighter" : "Elite Fighter: This character gains plus one to their To Hit rolls on all melee attacks.",
    "energy" : "Energy: Once per round, this character may use the Overload rule twice in the same Attack.",
    "fury" : "Fury: Once per game, at the beginning of this character's activation this character can reduce all its defenses by 3 until this character's next activation. If used it gains plus one to attack damage, plus two to its Attack stat and three power counters. This effect lasts until the end of the round.",
    "heroic action" : "Heroic Action: The first attack this character makes each round gains +1 to damage.",
    "power master" : "Power master: When this character uses the overload rule the base damage of the overloaded attack is increased by 1.",
    "power thief" : "Power thief: When this character damages another character with a melee attack, the target loses one Power Counter (if possible), if this happens the attacker gains one Power Counter.",
    "power transference" : "Power transference: At the beginning of this character's activation, it can transfer up to X Power Counters to a friendly model within 4 inches.",
    "sharpshooter" : "Sharpshooter: This character may reroll one of the dice To Hit dice each time they make a Ranged To Hit roll.",
    "solid" : "Solid: This character cannot use Defensive Improvements."
};